# Generated by Django 3.0.4 on 2020-03-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('observ', models.CharField(choices=[('F', 'FERIADO'), ('R', 'RECESSO'), ('P', 'PONTO FACULTATIVO'), ('L', 'DIA NÃO LETIVO')], default='F', max_length=1)),
            ],
        ),
    ]
